[package]
name = "moofish"
version = "0.1.0"
edition = "2021"

[lib]
name = "moofish"
path = "src/lib.rs"

[[bin]]
name = "moofish"
path = "src/main.rs"

[dependencies]
rand = { version = "0.8.*" }
rand_xorshift = { version = "0.3.*" }